wandb_version: 1

dropout:
  value: 0
ent-coef:
  value: 0.2
feature-extractor-hidden-dim:
  value: 128
feature-extractor-num-heads:
  value: 4
feature-extractor-num-layers:
  value: 1
learning-rate:
  value: 6.0e-12
policy-network-hidden-dim:
  value: 256
seed:
  value: 13
trading-dropout:
  value: 0.1
trading-ent-coef:
  value: 0.6
trading-feature-extractor-hidden-dim:
  value: 64
trading-feature-extractor-num-heads:
  value: 4
trading-feature-extractor-num-layers:
  value: 3
trading-learning-rate:
  value: 6.0e-05
trading-rl-gamma:
  value: 0.8
trading-train-steps:
  value: 2000
train-steps:
  value: 5
