wandb_version: 1

dropout:
  value: 0.1
ent-coef:
  value: 0.1
feature-extractor-hidden-dim:
  value: 128
feature-extractor-num-heads:
  value: 4
feature-extractor-num-layers:
  value: 2
learning-rate:
  value: 6.0e-13
policy-network-hidden-dim:
  value: 64
seed:
  value: 1
trading-dropout:
  value: 0
trading-ent-coef:
  value: 0.6
trading-feature-extractor-hidden-dim:
  value: 64
trading-feature-extractor-num-heads:
  value: 4
trading-feature-extractor-num-layers:
  value: 3
trading-learning-rate:
  value: 6.0e-05
trading-rl-gamma:
  value: 0.8
trading-train-steps:
  value: 1000
train-steps:
  value: 5
