wandb_version: 1

dropout:
  value: 0
ent-coef:
  value: 0.2
feature-extractor-hidden-dim:
  value: 64
feature-extractor-num-heads:
  value: 2
feature-extractor-num-layers:
  value: 3
learning-rate:
  value: 6.0e-12
policy-network-hidden-dim:
  value: 128
seed:
  value: 30
trading-dropout:
  value: 0
trading-ent-coef:
  value: 0.6
trading-feature-extractor-hidden-dim:
  value: 64
trading-feature-extractor-num-heads:
  value: 2
trading-feature-extractor-num-layers:
  value: 2
trading-learning-rate:
  value: 6.0e-06
trading-rl-gamma:
  value: 0.8
trading-train-steps:
  value: 1000
train-steps:
  value: 10
