wandb_version: 1

dropout:
  value: 0.1
ent-coef:
  value: 0.2
feature-extractor-hidden-dim:
  value: 64
feature-extractor-num-heads:
  value: 2
feature-extractor-num-layers:
  value: 3
learning-rate:
  value: 6.0e-12
policy-network-hidden-dim:
  value: 64
seed:
  value: 13
trading-dropout:
  value: 0.1
trading-ent-coef:
  value: 0.6
trading-feature-extractor-hidden-dim:
  value: 64
trading-feature-extractor-num-heads:
  value: 2
trading-feature-extractor-num-layers:
  value: 2
trading-learning-rate:
  value: 6.0e-05
trading-rl-gamma:
  value: 1
trading-train-steps:
  value: 2000
train-steps:
  value: 10
