wandb_version: 1

dropout:
  value: 0.1
ent-coef:
  value: 0.1
feature-extractor-hidden-dim:
  value: 128
feature-extractor-num-heads:
  value: 4
feature-extractor-num-layers:
  value: 2
learning-rate:
  value: 6.0e-13
policy-network-hidden-dim:
  value: 128
seed:
  value: 42
trading-dropout:
  value: 0.1
trading-ent-coef:
  value: 0.6
trading-feature-extractor-hidden-dim:
  value: 128
trading-feature-extractor-num-heads:
  value: 2
trading-feature-extractor-num-layers:
  value: 1
trading-learning-rate:
  value: 0.0006
trading-rl-gamma:
  value: 1
trading-train-steps:
  value: 2000
train-steps:
  value: 10
